obj-$(CONFIG_JZ_AIP_V20) += jz_aip_v20_drv.o \
			    jz_aip_v20_dbg.o \
			    jz_aip_v20_irq.o \
			    jz_aip_v20_bo.o  \
			    jz_aip_v20_core.o\
			    jz_aip_v20_nna.o\
			    jz_aip_v20_trace.o\
				jz_aip_v20_action.o
