
EXTRA_CFLAGS += -I$(src)/include

obj-$(CONFIG_SOUND) += audio_dsp.o audio_debug.o

obj-$(CONFIG_SOUND) += host/PRJ007/audio_aic.o
obj-$(CONFIG_SOUND) += inner_codecs/PRJ007/codec.o
obj-$(CONFIG_SOUND) += host/PRJ007/dmic/as-fmtcov/as-fmtcov.o
obj-$(CONFIG_SOUND) += host/PRJ007/dmic/as-dbus/as-dbus.o
obj-$(CONFIG_SOUND) += host/PRJ007/dmic/as-dma/as-dma.o
obj-$(CONFIG_SOUND) += host/PRJ007/dmic/as-dmic/as-dmic.o
obj-$(CONFIG_SOUND) += boards/PRJ007_platform.o
