EXTRA_CFLAGS += -I$(src)/include

obj-$(CONFIG_SOUND) += audio_dsp.o audio_debug.o

obj-$(CONFIG_SOUND) += host/T23/audio_aic.o
obj-$(CONFIG_SOUND) += inner_codecs/T23/codec.o
obj-$(CONFIG_SOUND) += boards/t23_platform.o


