
EXTRA_CFLAGS += -I$(src)/include

obj-$(CONFIG_SOUND) += audio_dsp.o audio_debug.o

obj-$(CONFIG_SOUND) += host/T41/audio_aic.o
obj-$(CONFIG_SOUND) += inner_codecs/T41/codec.o
obj-$(CONFIG_SOUND) += host/T41/dmic/as-fmtcov/as-fmtcov.o
obj-$(CONFIG_SOUND) += host/T41/dmic/as-dbus/as-dbus.o
obj-$(CONFIG_SOUND) += host/T41/dmic/as-dma/as-dma.o
obj-$(CONFIG_SOUND) += host/T41/dmic/as-dmic/as-dmic.o
obj-$(CONFIG_SOUND) += boards/t41_platform.o
