

obj-$(CONFIG_COMMON_CLK) += clk.o clk-pll.o clk-div.o clk-bus.o power-gate.o

obj-$(CONFIG_CLK_T31)		+= clk-t31.o
obj-$(CONFIG_CLK_PRJ007)	+= clk-PRJ007.o
obj-$(CONFIG_CLK_PRJ008)	+= clk-PRJ008.o



