obj-y += ingenic_vpu.o
obj-$(CONFIG_JZ_VPU_KERN_ENCODE) += vpu_common.o
obj-$(CONFIG_JZ_VPU_KERN_ENCODE) += src/
subdir-ccflags-y += -Idrivers/video/ingenic_vpu/kernel_encode/include
subdir-ccflags-y += -Idrivers/video/ingenic_vpu/kernel_encode/include/h265
subdir-ccflags-y += -Idrivers/video/ingenic_vpu/kernel_encode/include/h264
subdir-ccflags-y += -Idrivers/video/ingenic_vpu/kernel_encode/include/jpeg
