obj-y			+= common/
obj-y			+= debug/
obj-y			+= core/

obj-$(CONFIG_SOC_X1000) += soc-x1000/
obj-$(CONFIG_SOC_X1800) += soc-x1800/
obj-$(CONFIG_SOC_T31) += soc-t31/
obj-$(CONFIG_SOC_C100) += soc-c100/

